### ISSUE TITLE
Frontend formdata yanlış gidiyor olabilir

### ISSUE THREAD

**Issue by sineckers** [thorakna/cycloneproject#65]
Postman üzerinden bu şekilde gönderilen veri düzgün çalışıyor.
![image](https://user-images.githubusercontent.com/26010736/145660522-c66e624a-852b-4dcd-a4e6-41dd7a7deb3a.png)

#64 pr da denedim beceremedim tekrar denenecek

**Comment by thorakna** [comment]
file verisi düzgün gelmiyor olabilir test edilecek

**Comment by thorakna** [comment]
file verisi test edildi, veride hata olmadığı anlaşıldı. Serverside verilerin işlenmesinde hata olduğu anlaşıldı. Hata düzeltildi.
